module.exports = {
  // Purchase for 2,400 Gil {image} from Maisenta (Purchase Tools) in New Gridania (x11, y11).
  purchase: { en: 'Purchase for {img2} {i0} {i1} from {3} {4} in {img5} {6} (x: {7}, y: {8}).' },
  eventQuestPurchase: { en: 'Purchase from {0} during the {i1} event.' },
  // Pre-order A Realm Reborn and register the promotional code on or before Tuesday, 31st December 2013.
  preOrder: { en: '{i0} {1} and register the promotional code on or before {2}.' },
  // Register or digitially upgrade to the Collector's Edition of A Realm Reborn on the Mog Station.
  collectorsEdition: { en: 'Register or digitally upgrade to the {i0} of {i1} on the {2}.' },
  // Unlock the __achievement__ achievement, then speak to Jonathas at Apkallu Falls in Old Gridania (x: 10.5, y: 6.3).
  achievement: { en: 'Unlock the __achievement__ achievement, then speak to {0} at {1} in {img2} {3} (x: {4}, y: {5}).' },
  aquapolis: { en: 'Randomly awarded from treasure chests in {img0} {i1} from {2} onwards.' },
  duty: { en: 'Randomly awarded from a treasure chest in the level {0} duty {img1} \'{i2}\' (x: {3}, y: {4}).' },
  dutyFinalChest: { en: 'Randomly awarded from a treasure chest in level {0} duty {img1} \'{i2}\' (final chest).' },
  raid: { en: 'Randomly awarded from a treasure chest in level {0} raid {img1} \'{i2}\' (final chest).' },
  trial: { en: 'Randomly awarded from a treasure chest in level {0} trial {img1} \'{i2}\' (final chest).' },
  pvp: { en: 'Randomly awarded after winning level {0} PvP match {img1} \'{i2}\'.' },
  eventQuest: { en: 'Complete the level {0} {i1} quest {img3} \'{i2}\'.' },
  fate: { en: 'Achieve gold rating in the level {0} FATE {img1} \'{i2}\' in {img3} {4} (x: {5}, y: {6}).' },
  diademFate: { en: 'Randomly awarded after achieving gold rating in the level {0} {img1} {2} FATE {img3} \'{i4}\'.' },
  fateUnknown: { en: 'Achieve gold rating in the level {0} FATE {img1} \'{i2}\' in {img3} {4}.' },
  gilAfterFate: { en: 'Purchase for {img2} {i0} {i1} from {3} in {img4} {5} (x: {6}, y: {7}) after completing the level {8} FATE {img9} \'{i10}\' (x: {11}, y: {12}).' },
  itemAccursedHoard: { en: 'Randomly awarded from a {i0}, after obtaining a {1} within {img2} {3}.' },
  quest: { en: 'Complete the level {0} {1} quest {img2} \'{i3}\' from {4} in {img5} {6} (x: {7}, y: {8}).' },
  msq: { en: 'Complete the level {0} {1} main scenario quest {img2} \'{i3}\' from {4} in {img5} {6} (x: {7}, y: {8}).' },
  timewornMap: { en: 'Randomly awarded from the treasure chest after completing a level {0} (solo) {img1} {i2}.' },
  timewornMapFullParty: { en: 'Randomly awarded from the treasure chest after completing a level {0} (full party) {img1} {i2}.' },
  craft: { en: 'Crafted from a level {0} {i1} recipe{2} with {3}.' },
  craftShort: { en: 'Crafted from a level {0} {i1} recipe{2}.' },
  fishing: { en: 'Gathered by a {i0} at {1} in {img2} {i3} (x: {4}, y: {5}) using {6} as bait (level {7}).' },
  fishingDesynth: { en: 'Desynthesise {i0} as a {i1}, gathered by a {i2} at {3} in {img4} {i5} (x: {6}, y: {7}) mooching {8} (level {9}).' },
  fishingDoubleMooch: { en: 'Double-mooched by a {i0} at {1} in {img2} {i3} (x: {4}, y: {5}) using {6} as bait (level {7}) to catch a {8}, mooched to catch a {9}.'},
  fishingSpearfishing: { en: 'Spearfished from a {0} node by a {i1} using a {2} at {3} in {img4} {i5} (x: {6}, y: {7}) after catching {8} {9} (level {10}) with a {11}.' },
  achievementCertificate: { en: 'Purchase for {i0} {i1} {img2} from {3} at {4} in {img5} {6} (x: {7}, y: {8}).' },
  veteranReward: { en: 'Received as mail from a {i0} for subscribing for {1} days.' },
  gather: { en: 'Gathered by a level {0} {i1} at an unspoiled node{2} in {img3} {4} (x: {5}, y: {6}) at {7} (slot {8}).' },
  mogStation: { en: 'Purchase directly from the {i0}.' },
  beastTribe: { en: 'Achieve {0} reputation with the {i1} Beast Tribe, then purchase for {img4} {i2} {i3} from {5} {6} in {img7} {8} (x: {9}, y: {10}).'},
  squareEnixStore: { en: 'Purchase {i0} on the {i1} and register the promotional code on or before {2}.' },
  retainerVenture: { en: 'Randomly awarded from the {1} level {0} {img2} {i3} {i4} retainer venture.' },
  gardening: { en: 'Cultivate {img0} {i1}.' },
  wondrousTails: { en: 'Randomly awarded when completing {0} lines of {img1} {i2}.' },
  fanFestival: { en: 'Attend the {y0} fan festival in {1}.' },
  fanFestivalStream: { en: 'Purchase the online live stream of the {y0} fan festival in {1}.' }
};